### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [bloigge/QGisLayerStyleLoader#2]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by bloigge** [comment]
Hi - thank you for your help - I deleted the files, set the right path for issue tracking #1 and reuploaded the zip file.

**Comment by pcav** [comment]
They seem still present in the repo though.

**Comment by bloigge** [comment]
Sorry - my fault. Just updated the zip file which I uploaded to osgeo.org - not the repo here.
